export const GET_ROLES = 'GET_ROLES';
export const ROLES_LOADING = 'ROLES_LOADING';
export const SET_ROLES_SEARCH = 'SET_ROLES_SEARCH';
export const SET_SHOW_MODAL = 'SET_SHOW_MODAL';
export const ADD_ROLE = 'ADD_ROLE';
export const CLEAR_SEARCH_DATA = 'CLEAR_SEARCH_DATA';
export const SET_UPDATE_ROLE = 'SET_UPDATE_ROLE';